### PR TITLE
Merged various branches

### PR DESCRIPTION
**Pull request by KoenLav**
Please don't accept/merge this one right away, would like to discuss with @JakeArkleyTombola and @codlab first.

### CODE REVIEW

**Comment by KoenLav** [comment]
@JakeArkleyTombola @codlab

Could you guys clarify the changes you made?

For which specific use-cases where they required?

**Comment by codlab** [comment]
No problem. In the commit 92b9ea7057b8d5c6b072f1c24012d45195bce69e, an issue was detected using (only) iOS 10+ versions :
  - if no call to read was made after sending any data, nothing is fired
  - if a call to connect to a peerAddress or peerPort which were invalid (one or both), it hung and never. A modification is made at two point of the file for this particular issue :

  - add a timeout to connect to prevent hung
  - improve socketDidDisconnecting and check in another branch if a connect callback is still available (since connect callback are nil-led when sent) ; in such case, fire it with NO + err, then assign nil to it


bugs discovered while developping an app to manage remote mining software and testing those cases :

- unreachable ip address
- invalid port address for a proper ip address (reachable)
- send improper command for the given mining software's protocol
- send proper command for the given mining software's protocol

The previous mentionned commit has been updated with in-file comments related to this current one. Accessible here https://github.com/NonOpn/cordova-plugin-chrome-apps-sockets-tcp/commit/92b9ea7057b8d5c6b072f1c24012d45195bce69e

**Comment by KoenLav** [comment]
Thanks @codlab!

@JakeArkleyTombola could you clarify the changes you made as well, there are a lot of commits :)

**Comment by webgroup4business** [comment]
Can you merge this commit? It resolve an important issue on iOS!!

**Comment by KoenLav** [comment]
Are you experiencing the issue as described by codlab
?

**Comment by stephio** [comment]
Hi all,

my users reported regular crashes of their apps since iOS 11. I also hope this commit would fix it hopefully.

**Comment by JakeArkleyTombola** [comment]
Hi there, very sorry for the delay.

The main changes I made were:
- Handling of ClosedChannelException and NotYetConnectedException on the native Android side
- Standardised the error codes within the JS interface, since error codes from Android would differ greatly from iOS

**Comment by KoenLav** [comment]
@JakeArkleyTombola @codlab thanks for replying!

Could you both sign the contributor license so we can go ahead and merge this?

**Comment by JakeArkleyTombola** [comment]
Sure! How do I sign it? lol Should I have received an email?

**Comment by KoenLav** [comment]
Please visit: https://cla.developers.google.com/

Complete the signing.

And afterwards reply here (to re-run the tests).

**Comment by KoenLav** [comment]
@agrieve do you think I could be added to this repository as a maintainer?

**Comment by JakeArkleyTombola** [comment]
Signed the CLA @KoenLav :)

**Comment by agrieve** [comment]
Negative on adding you as a maintainer. If you'd like to fork it though, I'd be happy to update this repo to say "development moved over there".

**Comment by KoenLav** [comment]
@agrieve consider it done (it is done).

Can I also reuse the old name to publish the plugin?

**Pull request closed without merging**
